POST http://localhost:4230/auth/register
Content-Type: application/json

{
    "username": "Micel Doangs",
    "email": "gamingvalorant590@gmail.com",
    "password": "P@nasonic22",
    "description": "ga ada males buat deskripsi"
}
###
POST http://localhost:4230/auth/verify-email?token=7fdc1078449e8a2a1a3c56984073a143be6446e248d651d470ea3f758739b7c

###
POST http://localhost:4230/auth/login
Content-Type: application/json

{
    "email": "gamingvalorant590@gmail.com",
    "password": "P@nasonic22"
}

###
GET http://localhost:4230/tes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJuYW1lIjoiTWljZWwgRG9hbmdzIiwiZW1haWwiOiJnYW1pbmd2YWxvcmFudDU5MEBnbWFpbC5jb20iLCJ1c2VySWQiOjF9LCJpYXQiOjE3NzE4MTczNDQsImV4cCI6MTc3MTgxODI0NH0.hJGkYMUrVr7OgZ8EYLdShHfa5h-8v8m85UYHquCDViI
###
POST http://localhost:4230/auth/refresh-token