POST http://localhost:4230/auth/register
Content-Type: application/json

{
    "username": "Micel Doangs",
    "email": "gamingvalorant590@gmail.com",
    "password": "P@nasonic22",
    "description": "ga ada males buat deskripsi"
}
###
POST http://localhost:4230/auth/verify-email?token=7fdc1078449e8a2a1a3c56984073a143be6446e248d651d470ea3f758739b7c